package com.melissadata;

public class mdProfilerJNI {
	static {
		try {
			System.loadLibrary("mdProfilerJavaWrapper");
		} catch (UnsatisfiedLinkError ule) {
			System.out.println(ule);
			System.out.println("java.library.path="+System.getProperty("java.library.path"));
		}
	}

	public final static native long mdProfilerCreate();
	public final static native void mdProfilerDestroy(long I);
	public final static native int SetLicenseString(long I,String license);
	public final static native void SetPathToProfilerDataFiles(long I,String path);
	public final static native void SetFileName(long I,String fileName);
	public final static native void SetAppendMode(long I,int appendMode);
	public final static native void SetUserName(long I,String userName);
	public final static native String GetUserName(long I);
	public final static native void SetTableName(long I,String tableName);
	public final static native String GetTableName(long I);
	public final static native void SetJobName(long I,String jobName);
	public final static native String GetJobName(long I);
	public final static native void SetJobDescription(long I,String jobDescription);
	public final static native String GetJobDescription(long I);
	public final static native void SetSortAnalysis(long I,int sortAnalysis);
	public final static native void SetMatchUpAnalysis(long I,int matchUpAnalysis);
	public final static native void SetRightFielderAnalysis(long I,int rightFielderAnalysis);
	public final static native void SetDataAggregation(long I,int dataAggregation);
	public final static native int InitializeDataFiles(long I);
	public final static native String GetInitializeErrorString(long I);
	public final static native String GetBuildNumber(long I);
	public final static native String GetDatabaseDate(long I);
	public final static native String GetLicenseExpirationDate(long I);
	public final static native String GetProfileStartDateTime(long I);
	public final static native String GetProfileEndDateTime(long I);
	public final static native String GetColumnTypeEnum(long I);
	public final static native String GetColumnTypeDescription(long I,int columnType);
	public final static native int ParseColumnTypeDescription(long I,String columnTypeStr);
	public final static native String GetDataTypeEnum(long I);
	public final static native String GetDataTypeDescription(long I,int dataType);
	public final static native int ParseDataTypeDescription(long I,String dataTypeStr);
	public final static native String GetResultCodeEnum(long I);
	public final static native String GetResultCodeDescription(long I,String resultStr);
	public final static native void AddColumn(long I,String columnName,int columnType,int dataType);
	public final static native int SetColumnCustomPattern(long I,String columnName,String regEx);
	public final static native int SetColumnValueRange(long I,String columnName,String fromStr,String toStr);
	public final static native int SetColumnDefaultValue(long I,String columnName,String value);
	public final static native void SetColumnSize(long I,String columnName,int size);
	public final static native void SetColumnPrecision(long I,String columnName,int precision);
	public final static native void SetColumnScale(long I,String columnName,int scale);
	public final static native void SetColumnIgnoreOnError(long I,String columnName,int ignore);
	public final static native void StartProfiling(long I);
	public final static native void SetColumn(long I,String columnName,String content);
	public final static native void SetColumnNull(long I,String columnName);
	public final static native String GetColumnValue(long I,String columnName);
	public final static native void AddRecord(long I);
	public final static native String GetResults(long I,String columnName);
	public final static native void SetTextQualifier(long I,String qualifier);
	public final static native void SetColumnDelimiter(long I,String delimiter);
	public final static native void SetRowDelimiter(long I,String delimiter);
	public final static native String AddDelimitedRecord(long I,String record);
	public final static native void ProfileData(long I);
	public final static native int GetTableRecordCount(long I);
	public final static native int GetTableRecordEmptyCount(long I);
	public final static native int GetTableRecordNullCount(long I);
	public final static native int GetTableEmbeddedRowDelimiterCount(long I);
	public final static native int GetTableNotAllFieldsPresentCount(long I);
	public final static native int GetTableExtraFieldsPresentCount(long I);
	public final static native int GetTableUnbalancedTextQualifiersCount(long I);
	public final static native int GetTableUnescapedEmbeddedTextQualifiersCount(long I);
	public final static native int GetTableExactMatchDistinctCount(long I);
	public final static native int GetTableExactMatchDupesCount(long I);
	public final static native int GetTableExactMatchLargestGroup(long I);
	public final static native int GetTableContactMatchDistinctCount(long I);
	public final static native int GetTableContactMatchDupesCount(long I);
	public final static native int GetTableContactMatchLargestGroup(long I);
	public final static native int GetTableHouseholdMatchDistinctCount(long I);
	public final static native int GetTableHouseholdMatchDupesCount(long I);
	public final static native int GetTableHouseholdMatchLargestGroup(long I);
	public final static native int GetTableAddressMatchDistinctCount(long I);
	public final static native int GetTableAddressMatchDupesCount(long I);
	public final static native int GetTableAddressMatchLargestGroup(long I);
	public final static native int GetColumnCount(long I);
	public final static native String GetColumnName(long I,int index);
	public final static native int GetColumnColumnType(long I,String columnName);
	public final static native int GetColumnDataType(long I,String columnName);
	public final static native int GetColumnSize(long I,String columnName);
	public final static native int GetColumnPrecision(long I,String columnName);
	public final static native int GetColumnScale(long I,String columnName);
	public final static native String GetColumnValueRangeFrom(long I,String columnName);
	public final static native String GetColumnValueRangeTo(long I,String columnName);
	public final static native String GetColumnDefaultValue(long I,String columnName);
	public final static native String GetColumnCustomPatterns(long I,String columnName);
	public final static native int GetColumnInferredDataType(long I,String columnName);
	public final static native int GetColumnInferredColumnType(long I,String columnName);
	public final static native int GetColumnSortation(long I,String columnName);
	public final static native double GetColumnSortationPercent(long I,String columnName);
	public final static native int GetColumnMostPopularCount(long I,String columnName);
	public final static native int GetColumnDistinctCount(long I,String columnName);
	public final static native int GetColumnUniqueCount(long I,String columnName);
	public final static native int GetColumnDefaultValueCount(long I,String columnName);
	public final static native int GetColumnBelowRangeCount(long I,String columnName);
	public final static native int GetColumnAboveRangeCount(long I,String columnName);
	public final static native int GetColumnAboveSizeCount(long I,String columnName);
	public final static native int GetColumnAbovePrecisionCount(long I,String columnName);
	public final static native int GetColumnAboveScaleCount(long I,String columnName);
	public final static native int GetColumnInvalidRegExCount(long I,String columnName);
	public final static native int GetColumnEmptyCount(long I,String columnName);
	public final static native int GetColumnNullCount(long I,String columnName);
	public final static native int GetColumnInvalidDataCount(long I,String columnName);
	public final static native int GetColumnInvalidUTF8Count(long I,String columnName);
	public final static native int GetColumnNonPrintingCharCount(long I,String columnName);
	public final static native int GetColumnDiacriticCharCount(long I,String columnName);
	public final static native int GetColumnForeignCharCount(long I,String columnName);
	public final static native int GetColumnAlphaOnlyCount(long I,String columnName);
	public final static native int GetColumnNumericOnlyCount(long I,String columnName);
	public final static native int GetColumnAlphaNumericCount(long I,String columnName);
	public final static native int GetColumnUpperCaseOnlyCount(long I,String columnName);
	public final static native int GetColumnLowerCaseOnlyCount(long I,String columnName);
	public final static native int GetColumnMixedCaseCount(long I,String columnName);
	public final static native int GetColumnSingleSpaceCount(long I,String columnName);
	public final static native int GetColumnMultiSpaceCount(long I,String columnName);
	public final static native int GetColumnLeadingSpaceCount(long I,String columnName);
	public final static native int GetColumnTrailingSpaceCount(long I,String columnName);
	public final static native int GetColumnMaxSpaces(long I,String columnName);
	public final static native int GetColumnMinSpaces(long I,String columnName);
	public final static native int GetColumnTotalSpaces(long I,String columnName);
	public final static native int GetColumnTotalWordBreaks(long I,String columnName);
	public final static native double GetColumnAvgSpaces(long I,String columnName);
	public final static native int GetColumnDecorationCharCount(long I,String columnName);
	public final static native int GetColumnProfanityCount(long I,String columnName);
	public final static native int GetColumnInconsistentDataCount(long I,String columnName);
	public final static native String GetColumnStringMaxValue(long I,String columnName);
	public final static native String GetColumnStringMinValue(long I,String columnName);
	public final static native String GetColumnStringQ1Value(long I,String columnName);
	public final static native String GetColumnStringMedValue(long I,String columnName);
	public final static native String GetColumnStringQ3Value(long I,String columnName);
	public final static native int GetColumnStringMaxLength(long I,String columnName);
	public final static native int GetColumnStringMinLength(long I,String columnName);
	public final static native double GetColumnStringAvgLength(long I,String columnName);
	public final static native int GetColumnStringQ1Length(long I,String columnName);
	public final static native int GetColumnStringMedLength(long I,String columnName);
	public final static native int GetColumnStringQ3Length(long I,String columnName);
	public final static native String GetColumnWordMaxValue(long I,String columnName);
	public final static native String GetColumnWordMinValue(long I,String columnName);
	public final static native String GetColumnWordQ1Value(long I,String columnName);
	public final static native String GetColumnWordMedValue(long I,String columnName);
	public final static native String GetColumnWordQ3Value(long I,String columnName);
	public final static native int GetColumnWordMaxLength(long I,String columnName);
	public final static native int GetColumnWordMinLength(long I,String columnName);
	public final static native double GetColumnWordAvgLength(long I,String columnName);
	public final static native int GetColumnWordQ1Length(long I,String columnName);
	public final static native int GetColumnWordMedLength(long I,String columnName);
	public final static native int GetColumnWordQ3Length(long I,String columnName);
	public final static native int GetColumnMaxWords(long I,String columnName);
	public final static native int GetColumnMinWords(long I,String columnName);
	public final static native double GetColumnAvgWords(long I,String columnName);
	public final static native double GetColumnNumericMaxValue(long I,String columnName);
	public final static native double GetColumnNumericMinValue(long I,String columnName);
	public final static native double GetColumnNumericAvgValue(long I,String columnName);
	public final static native double GetColumnNumericQ1Value(long I,String columnName);
	public final static native double GetColumnNumericQ1IntValue(long I,String columnName);
	public final static native double GetColumnNumericMedValue(long I,String columnName);
	public final static native double GetColumnNumericMedIntValue(long I,String columnName);
	public final static native double GetColumnNumericQ3Value(long I,String columnName);
	public final static native double GetColumnNumericQ3IntValue(long I,String columnName);
	public final static native double GetColumnNumericStdDevValue(long I,String columnName);
	public final static native String GetColumnDateMaxValue(long I,String columnName);
	public final static native String GetColumnDateMinValue(long I,String columnName);
	public final static native String GetColumnDateAvgValue(long I,String columnName);
	public final static native String GetColumnDateQ1Value(long I,String columnName);
	public final static native String GetColumnDateMedValue(long I,String columnName);
	public final static native String GetColumnDateQ3Value(long I,String columnName);
	public final static native String GetColumnTimeMaxValue(long I,String columnName);
	public final static native String GetColumnTimeMinValue(long I,String columnName);
	public final static native String GetColumnTimeAvgValue(long I,String columnName);
	public final static native String GetColumnTimeQ1Value(long I,String columnName);
	public final static native String GetColumnTimeMedValue(long I,String columnName);
	public final static native String GetColumnTimeQ3Value(long I,String columnName);
	public final static native int GetColumnDateNoCenturyCount(long I,String columnName);
	public final static native int GetColumnNameInconsistentOrderCount(long I,String columnName);
	public final static native int GetColumnNameMultipleNameCount(long I,String columnName);
	public final static native int GetColumnNameSuspiciousNameCount(long I,String columnName);
	public final static native int GetColumnStateCount(long I,String columnName);
	public final static native int GetColumnProvinceCount(long I,String columnName);
	public final static native int GetColumnStateProvinceNonStandardCount(long I,String columnName);
	public final static native int GetColumnStateProvinceInvalidCount(long I,String columnName);
	public final static native int GetColumnZipCodeCount(long I,String columnName);
	public final static native int GetColumnPlus4Count(long I,String columnName);
	public final static native int GetColumnZipCodeInvalidCount(long I,String columnName);
	public final static native int GetColumnPostalCodeCount(long I,String columnName);
	public final static native int GetColumnPostalCodeInvalidCount(long I,String columnName);
	public final static native int GetColumnZipCodePostalCodeInvalidCount(long I,String columnName);
	public final static native int GetColumnStateZipCodeMismatchCount(long I,String columnName);
	public final static native int GetColumnProvincePostalCodeMismatchCount(long I,String columnName);
	public final static native int GetColumnCountryNonStandardCount(long I,String columnName);
	public final static native int GetColumnCountryInvalidCount(long I,String columnName);
	public final static native int GetColumnEmailSyntaxCount(long I,String columnName);
	public final static native int GetColumnEmailMobileDomainCount(long I,String columnName);
	public final static native int GetColumnEmailMisspelledDomainCount(long I,String columnName);
	public final static native int GetColumnEmailSpamtrapDomainCount(long I,String columnName);
	public final static native int GetColumnEmailDisposableDomainCount(long I,String columnName);
	public final static native int GetColumnPhoneInvalidCount(long I,String columnName);
	public final static native int StartDataFrequency(long I,String columnName,int order);
	public final static native String GetDataFrequencyValue(long I,String columnName);
	public final static native int GetDataFrequencyCount(long I,String columnName);
	public final static native int GetNextDataFrequency(long I,String columnName);
	public final static native int StartLengthFrequency(long I,String columnName,int order);
	public final static native int GetLengthFrequencyValue(long I,String columnName);
	public final static native int GetLengthFrequencyCount(long I,String columnName);
	public final static native int GetNextLengthFrequency(long I,String columnName);
	public final static native int StartPatternFrequency(long I,String columnName,int order);
	public final static native String GetPatternFrequencyValue(long I,String columnName);
	public final static native String GetPatternFrequencyRegEx(long I,String columnName);
	public final static native String GetPatternFrequencyExample(long I,String columnName);
	public final static native int GetPatternFrequencyCount(long I,String columnName);
	public final static native int GetNextPatternFrequency(long I,String columnName);
	public final static native int StartDateFrequency(long I,String columnName,int order,int dateSpan);
	public final static native String GetDateFrequencyValue(long I,String columnName);
	public final static native int GetDateFrequencyCount(long I,String columnName);
	public final static native int GetNextDateFrequency(long I,String columnName);
	public final static native int StartSoundExFrequency(long I,String columnName,int order);
	public final static native String GetSoundExFrequencyValue(long I,String columnName);
	public final static native String GetSoundExFrequencyExample(long I,String columnName);
	public final static native int GetSoundExFrequencyCount(long I,String columnName);
	public final static native int GetNextSoundExFrequency(long I,String columnName);
	public final static native int StartWordFrequency(long I,String columnName,int order);
	public final static native String GetWordFrequencyValue(long I,String columnName);
	public final static native int GetWordFrequencyCount(long I,String columnName);
	public final static native int GetNextWordFrequency(long I,String columnName);
	public final static native int StartWordLengthFrequency(long I,String columnName,int order);
	public final static native int GetWordLengthFrequencyValue(long I,String columnName);
	public final static native int GetWordLengthFrequencyCount(long I,String columnName);
	public final static native int GetNextWordLengthFrequency(long I,String columnName);
	public final static native void SetReserved(long I,String key,String value);
	public final static native String GetReserved(long I,String key);
}
